### PR TITLE
Add cmath lib to fix the compilation error

### PR DESCRIPTION
**Pull request by jmakov**
Currently the project fails to build on Ubuntu 18.04 with the following error:
`latency_measurements.hpp:65:40: error: ‘round’ is not a member of ‘std’`

This PR fixes this.

### CODE REVIEW

**Comment by RafaGago** [comment]
Thanks for this!
